name: 'NeoCustom Action'
description: 'Custom GitHub Action to greet and log time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  root-files:
    description: 'JSON list of filenames in the root directory'
runs:
  using: 'node20'
  main: 'dist/index.js'
